// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_friend_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_friend_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_friend_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_friend_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_friend_2eproto;
namespace example_service {
class GetfriendsListRequest;
class GetfriendsListRequestDefaultTypeInternal;
extern GetfriendsListRequestDefaultTypeInternal _GetfriendsListRequest_default_instance_;
class GetfriendsListResponse;
class GetfriendsListResponseDefaultTypeInternal;
extern GetfriendsListResponseDefaultTypeInternal _GetfriendsListResponse_default_instance_;
class ResultCode;
class ResultCodeDefaultTypeInternal;
extern ResultCodeDefaultTypeInternal _ResultCode_default_instance_;
}  // namespace example_service
PROTOBUF_NAMESPACE_OPEN
template<> ::example_service::GetfriendsListRequest* Arena::CreateMaybeMessage<::example_service::GetfriendsListRequest>(Arena*);
template<> ::example_service::GetfriendsListResponse* Arena::CreateMaybeMessage<::example_service::GetfriendsListResponse>(Arena*);
template<> ::example_service::ResultCode* Arena::CreateMaybeMessage<::example_service::ResultCode>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace example_service {

// ===================================================================

class ResultCode PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:example_service.ResultCode) */ {
 public:
  inline ResultCode() : ResultCode(nullptr) {};
  virtual ~ResultCode();

  ResultCode(const ResultCode& from);
  ResultCode(ResultCode&& from) noexcept
    : ResultCode() {
    *this = ::std::move(from);
  }

  inline ResultCode& operator=(const ResultCode& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResultCode& operator=(ResultCode&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResultCode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResultCode* internal_default_instance() {
    return reinterpret_cast<const ResultCode*>(
               &_ResultCode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResultCode& a, ResultCode& b) {
    a.Swap(&b);
  }
  inline void Swap(ResultCode* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResultCode* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResultCode* New() const final {
    return CreateMaybeMessage<ResultCode>(nullptr);
  }

  ResultCode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResultCode>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResultCode& from);
  void MergeFrom(const ResultCode& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResultCode* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "example_service.ResultCode";
  }
  protected:
  explicit ResultCode(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_friend_2eproto);
    return ::descriptor_table_friend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMsgFieldNumber = 2,
    kErrorCodeFieldNumber = 1,
  };
  // bytes error_msg = 2;
  void clear_error_msg();
  const std::string& error_msg() const;
  void set_error_msg(const std::string& value);
  void set_error_msg(std::string&& value);
  void set_error_msg(const char* value);
  void set_error_msg(const void* value, size_t size);
  std::string* mutable_error_msg();
  std::string* release_error_msg();
  void set_allocated_error_msg(std::string* error_msg);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_msg();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_msg(
      std::string* error_msg);
  private:
  const std::string& _internal_error_msg() const;
  void _internal_set_error_msg(const std::string& value);
  std::string* _internal_mutable_error_msg();
  public:

  // int32 error_code = 1;
  void clear_error_code();
  ::PROTOBUF_NAMESPACE_ID::int32 error_code() const;
  void set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_error_code() const;
  void _internal_set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:example_service.ResultCode)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_msg_;
  ::PROTOBUF_NAMESPACE_ID::int32 error_code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_friend_2eproto;
};
// -------------------------------------------------------------------

class GetfriendsListRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:example_service.GetfriendsListRequest) */ {
 public:
  inline GetfriendsListRequest() : GetfriendsListRequest(nullptr) {};
  virtual ~GetfriendsListRequest();

  GetfriendsListRequest(const GetfriendsListRequest& from);
  GetfriendsListRequest(GetfriendsListRequest&& from) noexcept
    : GetfriendsListRequest() {
    *this = ::std::move(from);
  }

  inline GetfriendsListRequest& operator=(const GetfriendsListRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetfriendsListRequest& operator=(GetfriendsListRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetfriendsListRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetfriendsListRequest* internal_default_instance() {
    return reinterpret_cast<const GetfriendsListRequest*>(
               &_GetfriendsListRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetfriendsListRequest& a, GetfriendsListRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetfriendsListRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetfriendsListRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetfriendsListRequest* New() const final {
    return CreateMaybeMessage<GetfriendsListRequest>(nullptr);
  }

  GetfriendsListRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetfriendsListRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetfriendsListRequest& from);
  void MergeFrom(const GetfriendsListRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetfriendsListRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "example_service.GetfriendsListRequest";
  }
  protected:
  explicit GetfriendsListRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_friend_2eproto);
    return ::descriptor_table_friend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
  };
  // uint32 user_id = 1;
  void clear_user_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_user_id() const;
  void _internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:example_service.GetfriendsListRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 user_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_friend_2eproto;
};
// -------------------------------------------------------------------

class GetfriendsListResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:example_service.GetfriendsListResponse) */ {
 public:
  inline GetfriendsListResponse() : GetfriendsListResponse(nullptr) {};
  virtual ~GetfriendsListResponse();

  GetfriendsListResponse(const GetfriendsListResponse& from);
  GetfriendsListResponse(GetfriendsListResponse&& from) noexcept
    : GetfriendsListResponse() {
    *this = ::std::move(from);
  }

  inline GetfriendsListResponse& operator=(const GetfriendsListResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetfriendsListResponse& operator=(GetfriendsListResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetfriendsListResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetfriendsListResponse* internal_default_instance() {
    return reinterpret_cast<const GetfriendsListResponse*>(
               &_GetfriendsListResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetfriendsListResponse& a, GetfriendsListResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetfriendsListResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetfriendsListResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetfriendsListResponse* New() const final {
    return CreateMaybeMessage<GetfriendsListResponse>(nullptr);
  }

  GetfriendsListResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetfriendsListResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetfriendsListResponse& from);
  void MergeFrom(const GetfriendsListResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetfriendsListResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "example_service.GetfriendsListResponse";
  }
  protected:
  explicit GetfriendsListResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_friend_2eproto);
    return ::descriptor_table_friend_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFriendFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // repeated bytes friend = 2;
  int friend__size() const;
  private:
  int _internal_friend__size() const;
  public:
  void clear_friend_();
  const std::string& friend_(int index) const;
  std::string* mutable_friend_(int index);
  void set_friend_(int index, const std::string& value);
  void set_friend_(int index, std::string&& value);
  void set_friend_(int index, const char* value);
  void set_friend_(int index, const void* value, size_t size);
  std::string* add_friend_();
  void add_friend_(const std::string& value);
  void add_friend_(std::string&& value);
  void add_friend_(const char* value);
  void add_friend_(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& friend_() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_friend_();
  private:
  const std::string& _internal_friend_(int index) const;
  std::string* _internal_add_friend_();
  public:

  // .example_service.ResultCode result = 1;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  const ::example_service::ResultCode& result() const;
  ::example_service::ResultCode* release_result();
  ::example_service::ResultCode* mutable_result();
  void set_allocated_result(::example_service::ResultCode* result);
  private:
  const ::example_service::ResultCode& _internal_result() const;
  ::example_service::ResultCode* _internal_mutable_result();
  public:
  void unsafe_arena_set_allocated_result(
      ::example_service::ResultCode* result);
  ::example_service::ResultCode* unsafe_arena_release_result();

  // @@protoc_insertion_point(class_scope:example_service.GetfriendsListResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> friend__;
  ::example_service::ResultCode* result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_friend_2eproto;
};
// ===================================================================

class FriendServiceRpc_Stub;

class FriendServiceRpc : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline FriendServiceRpc() {};
 public:
  virtual ~FriendServiceRpc();

  typedef FriendServiceRpc_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void GetfriendsList(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::example_service::GetfriendsListRequest* request,
                       ::example_service::GetfriendsListResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(FriendServiceRpc);
};

class FriendServiceRpc_Stub : public FriendServiceRpc {
 public:
  FriendServiceRpc_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  FriendServiceRpc_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~FriendServiceRpc_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements FriendServiceRpc ------------------------------------------

  void GetfriendsList(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::example_service::GetfriendsListRequest* request,
                       ::example_service::GetfriendsListResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(FriendServiceRpc_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResultCode

// int32 error_code = 1;
inline void ResultCode::clear_error_code() {
  error_code_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResultCode::_internal_error_code() const {
  return error_code_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResultCode::error_code() const {
  // @@protoc_insertion_point(field_get:example_service.ResultCode.error_code)
  return _internal_error_code();
}
inline void ResultCode::_internal_set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  error_code_ = value;
}
inline void ResultCode::set_error_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:example_service.ResultCode.error_code)
}

// bytes error_msg = 2;
inline void ResultCode::clear_error_msg() {
  error_msg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ResultCode::error_msg() const {
  // @@protoc_insertion_point(field_get:example_service.ResultCode.error_msg)
  return _internal_error_msg();
}
inline void ResultCode::set_error_msg(const std::string& value) {
  _internal_set_error_msg(value);
  // @@protoc_insertion_point(field_set:example_service.ResultCode.error_msg)
}
inline std::string* ResultCode::mutable_error_msg() {
  // @@protoc_insertion_point(field_mutable:example_service.ResultCode.error_msg)
  return _internal_mutable_error_msg();
}
inline const std::string& ResultCode::_internal_error_msg() const {
  return error_msg_.Get();
}
inline void ResultCode::_internal_set_error_msg(const std::string& value) {
  
  error_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ResultCode::set_error_msg(std::string&& value) {
  
  error_msg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:example_service.ResultCode.error_msg)
}
inline void ResultCode::set_error_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:example_service.ResultCode.error_msg)
}
inline void ResultCode::set_error_msg(const void* value,
    size_t size) {
  
  error_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:example_service.ResultCode.error_msg)
}
inline std::string* ResultCode::_internal_mutable_error_msg() {
  
  return error_msg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ResultCode::release_error_msg() {
  // @@protoc_insertion_point(field_release:example_service.ResultCode.error_msg)
  return error_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ResultCode::set_allocated_error_msg(std::string* error_msg) {
  if (error_msg != nullptr) {
    
  } else {
    
  }
  error_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_msg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:example_service.ResultCode.error_msg)
}
inline std::string* ResultCode::unsafe_arena_release_error_msg() {
  // @@protoc_insertion_point(field_unsafe_arena_release:example_service.ResultCode.error_msg)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return error_msg_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ResultCode::unsafe_arena_set_allocated_error_msg(
    std::string* error_msg) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_msg != nullptr) {
    
  } else {
    
  }
  error_msg_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_msg, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:example_service.ResultCode.error_msg)
}

// -------------------------------------------------------------------

// GetfriendsListRequest

// uint32 user_id = 1;
inline void GetfriendsListRequest::clear_user_id() {
  user_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GetfriendsListRequest::_internal_user_id() const {
  return user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GetfriendsListRequest::user_id() const {
  // @@protoc_insertion_point(field_get:example_service.GetfriendsListRequest.user_id)
  return _internal_user_id();
}
inline void GetfriendsListRequest::_internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  user_id_ = value;
}
inline void GetfriendsListRequest::set_user_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:example_service.GetfriendsListRequest.user_id)
}

// -------------------------------------------------------------------

// GetfriendsListResponse

// .example_service.ResultCode result = 1;
inline bool GetfriendsListResponse::_internal_has_result() const {
  return this != internal_default_instance() && result_ != nullptr;
}
inline bool GetfriendsListResponse::has_result() const {
  return _internal_has_result();
}
inline void GetfriendsListResponse::clear_result() {
  if (GetArena() == nullptr && result_ != nullptr) {
    delete result_;
  }
  result_ = nullptr;
}
inline const ::example_service::ResultCode& GetfriendsListResponse::_internal_result() const {
  const ::example_service::ResultCode* p = result_;
  return p != nullptr ? *p : *reinterpret_cast<const ::example_service::ResultCode*>(
      &::example_service::_ResultCode_default_instance_);
}
inline const ::example_service::ResultCode& GetfriendsListResponse::result() const {
  // @@protoc_insertion_point(field_get:example_service.GetfriendsListResponse.result)
  return _internal_result();
}
inline void GetfriendsListResponse::unsafe_arena_set_allocated_result(
    ::example_service::ResultCode* result) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(result_);
  }
  result_ = result;
  if (result) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:example_service.GetfriendsListResponse.result)
}
inline ::example_service::ResultCode* GetfriendsListResponse::release_result() {
  auto temp = unsafe_arena_release_result();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::example_service::ResultCode* GetfriendsListResponse::unsafe_arena_release_result() {
  // @@protoc_insertion_point(field_release:example_service.GetfriendsListResponse.result)
  
  ::example_service::ResultCode* temp = result_;
  result_ = nullptr;
  return temp;
}
inline ::example_service::ResultCode* GetfriendsListResponse::_internal_mutable_result() {
  
  if (result_ == nullptr) {
    auto* p = CreateMaybeMessage<::example_service::ResultCode>(GetArena());
    result_ = p;
  }
  return result_;
}
inline ::example_service::ResultCode* GetfriendsListResponse::mutable_result() {
  // @@protoc_insertion_point(field_mutable:example_service.GetfriendsListResponse.result)
  return _internal_mutable_result();
}
inline void GetfriendsListResponse::set_allocated_result(::example_service::ResultCode* result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete result_;
  }
  if (result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(result);
    if (message_arena != submessage_arena) {
      result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, result, submessage_arena);
    }
    
  } else {
    
  }
  result_ = result;
  // @@protoc_insertion_point(field_set_allocated:example_service.GetfriendsListResponse.result)
}

// repeated bytes friend = 2;
inline int GetfriendsListResponse::_internal_friend__size() const {
  return friend__.size();
}
inline int GetfriendsListResponse::friend__size() const {
  return _internal_friend__size();
}
inline void GetfriendsListResponse::clear_friend_() {
  friend__.Clear();
}
inline std::string* GetfriendsListResponse::add_friend_() {
  // @@protoc_insertion_point(field_add_mutable:example_service.GetfriendsListResponse.friend)
  return _internal_add_friend_();
}
inline const std::string& GetfriendsListResponse::_internal_friend_(int index) const {
  return friend__.Get(index);
}
inline const std::string& GetfriendsListResponse::friend_(int index) const {
  // @@protoc_insertion_point(field_get:example_service.GetfriendsListResponse.friend)
  return _internal_friend_(index);
}
inline std::string* GetfriendsListResponse::mutable_friend_(int index) {
  // @@protoc_insertion_point(field_mutable:example_service.GetfriendsListResponse.friend)
  return friend__.Mutable(index);
}
inline void GetfriendsListResponse::set_friend_(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:example_service.GetfriendsListResponse.friend)
  friend__.Mutable(index)->assign(value);
}
inline void GetfriendsListResponse::set_friend_(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:example_service.GetfriendsListResponse.friend)
  friend__.Mutable(index)->assign(std::move(value));
}
inline void GetfriendsListResponse::set_friend_(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  friend__.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:example_service.GetfriendsListResponse.friend)
}
inline void GetfriendsListResponse::set_friend_(int index, const void* value, size_t size) {
  friend__.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:example_service.GetfriendsListResponse.friend)
}
inline std::string* GetfriendsListResponse::_internal_add_friend_() {
  return friend__.Add();
}
inline void GetfriendsListResponse::add_friend_(const std::string& value) {
  friend__.Add()->assign(value);
  // @@protoc_insertion_point(field_add:example_service.GetfriendsListResponse.friend)
}
inline void GetfriendsListResponse::add_friend_(std::string&& value) {
  friend__.Add(std::move(value));
  // @@protoc_insertion_point(field_add:example_service.GetfriendsListResponse.friend)
}
inline void GetfriendsListResponse::add_friend_(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  friend__.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:example_service.GetfriendsListResponse.friend)
}
inline void GetfriendsListResponse::add_friend_(const void* value, size_t size) {
  friend__.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:example_service.GetfriendsListResponse.friend)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetfriendsListResponse::friend_() const {
  // @@protoc_insertion_point(field_list:example_service.GetfriendsListResponse.friend)
  return friend__;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetfriendsListResponse::mutable_friend_() {
  // @@protoc_insertion_point(field_mutable_list:example_service.GetfriendsListResponse.friend)
  return &friend__;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace example_service

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_friend_2eproto
